# TODO: Deal with the mess at some point
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

plugins:
  - rubocop-rspec

RSpec/SpecFilePathFormat:
  Enabled: false
